/* Main.c file generated by New Project wizard
 *
 * Created:   lun. nov. 1 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <stdint.h>
#include "seos.h"

int main (void){
	SEOS_Boot(); 	
	while(1) {
		SEOS_Dispatch();
		SEOS_Sleep();
	}
}
